--- 
$schemaver: 1.1
name: developer-portal-publish-process
type: Background Process
aliases:
short_description: The pipeline for getting documentation from swagger files into the Developer's Portal
assignment_group: gro:AD-Software Architecture
notes: 
maintained_by:
  - mhailstone
developed_by_byu: true
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: https://github.com/byu-oit/developer-portal-publish-process
  source_repo_url: https://github.com/byu-oit/developer-portal-publish-process
  swagger_urls:
microservice: false
technologies_used:
  - NodeJS
  - AWS CloudFormation
  - REST Web Services
  - JavaScript
  - HTML
  - Python
stages:
  development:
    urls:
      product_page: 
      physical_url: 
      virtual_url: 
    hosting_location: AWS
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software: repo-meta:production
      supports:
        software:
        service:
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: confidential
  env: dev
  team: AD-Software Architecture
  app: developer-portal-publish-process
federation_json_url: https://raw.githubusercontent.com/byu-oit/developer-portal-publish-process/master/.repo-meta.yml
